_target_: exp.ExpB.Exp_Model
net_params:
  name: LSTNet
  seq_len: ${forecast.seq_len}
  pred_len: ${forecast.pred_len}
  enc_in: ${data.data_params.enc_in}
  features: ${forecast.features}
  norm_type: seq
  lr: ${forecast.lr}
  #
  c_in: ${forecast.seq_len}
  c_out: ${forecast.pred_len}
  out_channels: 
  kernel_size:
  cell_type:
  hidden_size: 128
  num_layers:
  skip_cell_type: 
  skip_hidden_size: 
  skip_num_layers: 
  skip_size:
  ar_window:
  embedding_dim: 10
  dropout_rate: 0.2
  freq: h
