_target_: exp.ExpB.Exp_Model
net_params:
  name: D_PAD
  seq_len: ${forecast.seq_len}
  pred_len: ${forecast.pred_len}
  enc_in: ${data.data_params.enc_in}
  features: ${forecast.features}
  norm_type: seq # seq, batch, layer, no,revin
  lr: ${forecast.lr}

  #
  enc_hidden: 336
  dec_hidden: 336
  num_levels: 3
  dropout: 0.5
  K_IMP: 6
  RIN: 0
  num_heads: 1
