_target_: exp.ExpB.Exp_Model
net_params:
  #必须
  name: SparseTSF
  seq_len: ${forecast.seq_len}
  pred_len: ${forecast.pred_len}
  
  enc_in: ${data.data_params.enc_in}
  features: ${forecast.features} # input dimension
  norm_type: seq
  lr: ${forecast.lr}
  
  #
  period_len: ${data.data_params.period_len}