_target_: exp.ExpB.Exp_Model
net_params:
  #必须
  name: SCINet
  seq_len: ${forecast.seq_len}
  pred_len: ${forecast.pred_len}
  enc_in: ${data.data_params.enc_in}
  features: ${forecast.features} # input dimension
  norm_type: seq
  lr: ${forecast.lr}
  
  # 不常用的参数
  d_layers: 1
  dropout: 0.1

