_target_: lightning.pytorch.trainer.Trainer
accelerator: cpu
devices: [1]
max_epochs: 3
min_epochs: 3
limit_train_batches: 200
check_val_every_n_epoch: 2
# limit_val_batches: 1 # 每轮的验证批次数
# limit_test_batches: 1 # 每轮的测试批次数
fast_dev_run: False

