_target_: lightning.pytorch.trainer.Trainer
accelerator: gpu
devices: 2
max_epochs: 30
min_epochs: 3
limit_train_batches: 100
check_val_every_n_epoch: 3
limit_val_batches: 3 # 每轮的验证批次数
limit_test_batches: 2 # 每轮的测试批次数
fast_dev_run: True

