_target_: exp.ExpA.Exp_Model
net_params:
  #必须
  name: TimeMixer
  seq_len: ${forecast.seq_len}
  pred_len: ${forecast.pred_len}
  label_len: 0 #非former为0
  enc_in: ${data.data_params.enc_in}
  features: ${forecast.features} # input dimension
  norm_type: no
  lr: ${forecast.lr}

  # timnet
  task_name: long_term_forecast
  e_layers: 2
  d_layers: 1
  factor: 3
  dec_in: ${data.data_params.enc_in}
  d_ff: 32
  d_model: 16
  embed: 32
  freq: ${data.data_params.freq}
  c_out: ${data.data_params.enc_in}
  top_k: 5
  num_kernels: 1
  dropout: 0.1
  output_attention: False
  down_sampling_layers: 3
  down_sampling_window: 2
  down_sampling_method: avg
  channel_independence: 1
  decomp_method: moving_avg
  moving_avg: 25
  use_norm: ${forecast.use_revin}
